name = "dcspark/projected-nft-whirlpool"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for the Projected NFT Whirlpool"

[repository]
user = "dcspark"
project = "projected-nft-whirlpool"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"
